---
- import_role:
    name: kernel4-common

- name: Wait for nodes to come back
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: 22
    search_regex: OpenSSH
    delay: 75
    timeout: 300
  with_items: "{{ groups.nodes }}"
  delegate_to: "{{ groups.master[0] }}"

- name: Remove kernel 3
  yum:
    name: kernel-3
    state: removed

- name: Confirm kernel version
  shell: uname -a
  register: kernel_version

- debug: var=kernel_version.stdout
