---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    failure-domain.beta.kubernetes.io/zone: nova
  name: pv-renku-gitlab
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  cinder:
    volumeID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  claimRef:
    namespace: renku
    name: renku-gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    failure-domain.beta.kubernetes.io/zone: nova
  name: pv-renku-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  cinder:
    volumeID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  claimRef:
    namespace: renku
    name: renku-postgresql
