---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renku-gitlab
  namespace: renku
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renku-postgresql
  namespace: renku
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
