## Configuration file for deploying the renku chart at http://renku.mydomain.ch
---
variables_switchboard:
  mainURL:            &mainURL            renku.mydomain.ch                    ## Fill in with Renku domain
  baseURL:            &baseURL           https://renku.mydomain.ch             ## Fill in with Renku domain
  registryName:       &registryName       registry.renku.mydomain.ch           ## Fill in with Gitlab registry, including port if needed
  registryURL:        &registryURL        https://registry.renku.mydomain.ch   ## Fill in with Gitlab registry, including port if needed
  gitlabURL:          &gitlabURL          https://renku.mydomain.ch/gitlab     ## Alternatively, fill in with Gitlab domain (standalone)
  jupyterhubURL:      &jupyterhubURL      https://renku.mydomain.ch/jupyterhub ## Fill in with Renku domain
  gatewayURL:         &gatewayURL         https://renku.mydomain.ch/api        ## Fill in with Renku domain
  oauth_redirect_uri: &oauth_redirect_uri https://renku.mydomain.ch/api/auth/jupyterhub/token ## Fill in with Renku domain
  ingress_tls:        &ingress_tls        renku-mydomain-ch-tls           ## RFC1123 compliant name, no underscores please
  registry_tls:       &registry_tls       registry-renku-mydomain-ch-tls  ## RFC1123 compliant name, no underscores please

credentials:
  pass101: &global_gitlab_clientSecret                      ## Replace with gitlab client in keycloak
  pass102: &global_gitlab_postgresPassword                  ## Replace with a 64 CharString e.g. openssl rand -hex 32
  pass103: &global_gitlab_sudoToken                         ## Replace with gitlab sudo token
  pass104: &global_keycloak_postgresPassword                ## Replace with a 64 CharString e.g. openssl rand -hex 32
  pass105: &global_jupyterhub_postgresPassword              ## Replace with a 64 CharString e.g. openssl rand -hex 32 USED in pass 502
  pass106: &global_graph_tokenRepository                    ## Replace with a 64 CharString e.g. openssl rand -hex 32 ## openssl rand -hex 32
  pass107: &global_graph_dbEventLog                         ## Replace with a 64 CharString e.g. openssl rand -hex 32 ## openssl rand -hex 32
  pass108: &global_gateway_clientSecret                     ## Replace with gateway keycloak client
  pass109: &global_gateway_gitlabClientSecret               ## Replace with renku-ui gitlab client secret
  pass110: &global_gateway_gitlabClientId                   ## Replace with renku-ui gitlab client id

  pass201: &gitlab_password                                 ## Replace with a 64 CharString e.g. openssl rand -hex 32  (not needed if standalone) 
  pass202: &gitlab_sharedRunnersRegistrationToken           ## Replace with a 64 CharString e.g. openssl rand -hex 32 (not needed if standalone)

  pass301: &keycloak_password                               ## Replace with Keycloak password (if standalone) or with a 32 CharString
  pass401: &postgresql_postgresPassword                     ## Replace with Postgresql password (if standalone) or with a 32 CharString
  pass501: &nb_jupyterhub_hub_cookieSecret                  ## Replace with a 64 CharString e.g. openssl rand -hex 32
  pass502: &nb_jupyterhub_hub_db_url                        ## postgres+psycopg2://jupyterhub:<<ReplaceMeWithValueOfpass104>>@renku-postgresql:5432/jupyterhub
  pass503: &nb_jupyterhub_hub_services_notebooks_apiToken   ## Replace with a 64 CharString e.g. openssl rand -hex 32
  pass504: &nb_jupyterhub_hub_services_gateway_apiToken     ## Replace with a 64 CharString e.g. openssl rand -hex 32
  pass505: &nb_jupyterhub_proxy_secretToken                 ## Replace with a 64 CharString e.g. openssl rand -hex 32
  pass506: &nb_jupyterhub_auth_state_cryptoKey              ## Replace with a 64 CharString e.g. openssl rand -hex 32

  pass507: &nb_jupyterhub_auth_gitlab_clientId              ## Replace with jupyterhub gitlab client id
  pass508: &nb_jupyterhub_auth_gitlab_clientSecret          ## Replace with jupyterhub gitlab client secret
  pass601: &gateway_secretKey                               ## Replace with a 64 CharString e.g. openssl rand -hex 32
  pass701: &graph_sparql_password                           ## Replace with a 64 CharString e.g. openssl rand -hex 32

defaultResources: &defaultResources
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 512Mi

global:
  gitlab:
    clientSecret: *global_gitlab_clientSecret
    postgresDatabase: gitlabhq_production
    postgresUser: gitlab
    postgresPassword: *global_gitlab_postgresPassword
    urlPrefix: /gitlab
    sudoToken: *global_gitlab_sudoToken
  keycloak:
    postgresDatabase: keycloak
    postgresUser: keycloak
    postgresPassword: *global_keycloak_postgresPassword
  jupyterhub:
    postgresDatabase: jupyterhub
    postgresUser: jupyterhub
    postgresPassword: *global_jupyterhub_postgresPassword
  gateway:
    clientSecret: *global_gateway_clientSecret
    gitlabClientId: *global_gateway_gitlabClientId
    gitlabClientSecret: *global_gateway_gitlabClientSecret
  renku:
    https: true
    domain: *mainURL
  graph:
    tokenRepository:
      postgresPassword: *global_graph_tokenRepository
    dbEventLog:
      postgresPassword: *global_graph_dbEventLog
    jena:
      dataset: renku
  useHTTPS: true

gitlab:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: gitlab/gitlab-ce
    tag: 11.7.5-ce.0
  password: *gitlab_password
  ssh:
    externalPort: 22
    nodePortService:
      enabled: true
      nodePort: 32022
  persistence:
    existingClaim: renku-gitlab
  lfsObjects:
    enabled: true
    bucketName: lfs-objects
    connection: |-
      {
        'provider' => 'OpenStack',
        'openstack_auth_url' => 'https://keystone.---:5000/v3/auth/tokens',
        'openstack_username' => '---',
        'openstack_api_key' => '---',
        'openstack_domain_name' => 'Default',
        'openstack_project_id' => '---',
        'openstack_region' => '--',
        'openstack_temp_url_key' => '---'
      }
  registry:
    enabled: true
    externalUrl: *registryURL
    backendHealthcheck: false
    storage: |-
      {
        'swift' => {
          'authurl' => 'https://keystone.---:5000/v3',
          'username' => '---',
          'password' => '---',
          'region' => '--',
          'container' => 'registry',
          'tenantid' => '--',
          'domain' => '---'
        }
      }
    exposedAs: Ingress
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: '0' # Adjust to a reasonable value for production to avoid DOS attacks.
        nginx.ingress.kubernetes.io/proxy-request-buffering: 'off' # Needed if GitLab is behind this ingress
      hosts:
      - *registryName
      tls:
      - hosts:
        - *registryName
        secretName: *registry_tls
  resources:
    requests:
      cpu: 1500m
      memory: 10Gi
    limits:
      cpu: 1500m
      memory: 10Gi
  redis:
    master:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
  sharedRunnersRegistrationToken: *gitlab_sharedRunnersRegistrationToken

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: '0' # Adjust to a reasonable value for production to avoid DOS attacks.
    nginx.ingress.kubernetes.io/proxy-request-buffering: 'off' # Needed if GitLab is behind this ingress
  enabled: true
  hosts:
  - *mainURL
  tls:
  - hosts:
    - *mainURL
    secretName: *ingress_tls

keycloak:
  enabled: true
  keycloak:
    username: admin
    password: *keycloak_password
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi

postgresql:
  postgresPassword: *postgresql_postgresPassword
  persistence:
    existingClaim: renku-postgresql
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi

ui:
  ingress:
    enabled: false
  baseUrl: *baseURL
  gitlabUrl: *gitlabURL
  jupyterhubUrl: *jupyterhubURL
  gatewayUrl: *gatewayURL
  welcomePage:
    text: |
      ## First Time

      If you are here for your first time, we recommend you go through our
      [tutorial](https://renku.readthedocs.io/en/latest/user/firststeps.html).

      ## Help

      If you need help, the preferred way to reach us is via the
      [*Gitter channel*](https://gitter.im/SwissDataScienceCenter/renku ) or the issue
      tracker in our [GitHub repository](https://github.com/SwissDataScienceCenter/renku).
      You can also browse the [general Renku documentation](https://renku.readthedocs.org)
      as well as the [command-line interface docs](https://renku-python.readthedocs.org).

      ## renku.mydomain.ch

      Renku is under active development. We encourage you to have a look around,
      and we are doing our best to keep it stable, but please be aware that changes
      may be made without prior warning and could lead to service interruptions.

      We also kindly request that you do not upload datasets larger than 1GB for
      the time being. In the future, we will remove this restriction.

      ### Renku version 0.4.0 (May 28th 2019)

      See the [Release Notes](https://github.com/SwissDataScienceCenter/renku/releases/tag/0.4.0)
      for detailed information about the changes and improvements.

  resources:
    <<: *defaultResources

notebooks:
  serverOptions:
    cpu_request:
      default: 0.1
      options: [0.1, 0.5, 1.0, 2.0, 4.0]
    mem_request:
      default: 1G
      options: [1G, 2G, 4G]
    gpu_request:
      default: 0
      range: [0, 0] ## upgrade second value to number of GPUs per node
    defaultUrl:
      default: /lab
      options: [/lab]
    lfs_auto_fetch:
      default: false
  gitlab:
    ## specify the GitLab instance URL
    url: *gitlabURL
    registry:
      ## Set the default image registry
      host: *registryName
      ## Set the registry secret key
      secret: renku-notebooks-registry
  resources:
    <<: *defaultResources
  jupyterhub:
    rbac:
      enabled: true
    hub:
      cookieSecret: *nb_jupyterhub_hub_cookieSecret
      baseUrl: '/jupyterhub/'
      extraEnv:
        GITLAB_URL: *gitlabURL
        IMAGE_REGISTRY: *registryName
      db:
        type: postgres
        url: *nb_jupyterhub_hub_db_url
      services:
        notebooks:
          apiToken: *nb_jupyterhub_hub_services_notebooks_apiToken
        gateway:
          admin: true
          oauth_client_id: &gatewayClient gateway
          apiToken: *nb_jupyterhub_hub_services_gateway_apiToken
          oauth_redirect_uri: *oauth_redirect_uri
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /jupyterhub/hub/metrics
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 200m
          memory: 1Gi
    proxy:
      secretToken: *nb_jupyterhub_proxy_secretToken
      chp:
        resources:
          <<: *defaultResources
    auth:
      state:
        enabled: true
        cryptoKey: *nb_jupyterhub_auth_state_cryptoKey
      gitlab:
        clientId: *nb_jupyterhub_auth_gitlab_clientId
        clientSecret: *nb_jupyterhub_auth_gitlab_clientSecret
        callbackUrl: *jupyterhub_gitlab_callbackUrl

graph:
  enabled: true
  jena:
    admin:
      password: *sparql_password
    persistence:
      existingClaim: ## Replace with PVC
  gitlab:
    url: *gitlabURL
  webhookService:
    hookToken:
      secret: YzBjODA4NTlhZjUwODkxOQo=  ## Genereated with openssl rand -hex 8|base64
    eventsSynchronization:
      initialDelay: 2 minutes
      interval: 30 minutes
  tokenRepository:
    tokenEncryption:
      secret: YjVmMzAwYTkwNDk0Y2RhOQo=  ## Genereated with openssl rand -hex 8|base64
  sentry:
    sentryDsnRenkuGraph: ''   ## Used so as not to get the ERROR in the graph services logs, but stil get the error
gateway:
  graph:
    sparql:
      username: admin
      password: *graph_sparql_password
  keycloakUrl: *keycloakURL
  gitlabUrl: *gitlabURL
  jupyterhub:
    clientId: *gatewayClient
    clientSecret: *nb_jupyterhub_hub_services_gateway_apiToken
  secretKey: *gateway_secretKey
  resources:
    <<: *defaultResources
  redis:
    master:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi

tests:
  ## User accounts for running `helm test`
  ## Replace passwords with random strings in a production setup
  users_json:
   - username: bwayne
     firstName: Bruce
     lastName: Wayne
     email: bwayne@example.com
     password: ## Replace with a 64 CharString e.g. openssl rand -hex 32
   - username: ckent
     firstName: Clark
     lastName: Kent
     email: ckent@example.com
     password: ## Replace with a 64 CharString e.g. openssl rand -hex 32
