---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    # Fill in the admin email for the domain names
    # email: 
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-prod
