---
- name: Add ELRepo rpm key
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install ELRepo
  yum:
    name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: present

- name: Install kernel 4
  yum:
    name: kernel-ml
    state: latest
    update_cache: yes
    enablerepo: elrepo-kernel

- name: Set default kernel
  lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_DEFAULT=
    line: GRUB_DEFAULT=0
  register: grub_changed

- name: Recreate grub config
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub_changed["changed"]

- name: Restart machine
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  when: grub_changed["changed"]
